import type { LabelConfig, SalesState, SeatingMap } from './seating.types'

const NUMBERS: LabelConfig = { scheme: 'numbers', start: '1', direction: 'forward' }
const LETTERS: LabelConfig = { scheme: 'letters', start: 'A', direction: 'forward' }

/** A demo concert hall showing every element type, used on first load and on reset. */
export const SAMPLE_MAP: SeatingMap = {
  name: 'Riverside Hall',
  width: 1000,
  height: 780,
  background: '#f8fafc',
  categories: [
    {
      id: 'cat_vip',
      name: 'VIP',
      color: '#7c3aed',
      priceOptions: [{ id: 'po_vip', name: 'Regular', amount: 120000 }],
    },
    {
      id: 'cat_std',
      name: 'Standard',
      color: '#2563eb',
      priceOptions: [
        { id: 'po_std_adult', name: 'Adult', amount: 70000 },
        { id: 'po_std_student', name: 'Student', amount: 50000 },
      ],
    },
    {
      id: 'cat_table',
      name: 'Table',
      color: '#0d9488',
      priceOptions: [{ id: 'po_table', name: 'Regular', amount: 90000 }],
    },
    {
      id: 'cat_ga',
      name: 'Standing',
      color: '#ea580c',
      priceOptions: [{ id: 'po_ga', name: 'Regular', amount: 40000 }],
    },
  ],
  elements: [
    {
      id: 'stage',
      kind: 'shape',
      shape: 'rect',
      label: 'Stage',
      x: 500,
      y: 70,
      rotation: 0,
      width: 380,
      height: 80,
      fill: '#334155',
    },
    {
      id: 'center',
      kind: 'rows',
      label: 'Center',
      x: 500,
      y: 255,
      rotation: 0,
      categoryId: 'cat_vip',
      rowCount: 6,
      seatsPerRow: 14,
      seatSpacing: 22,
      rowSpacing: 26,
      curve: 40,
      rowLabels: LETTERS,
      rowLabelPosition: 'both',
      seatLabels: NUMBERS,
    },
    {
      id: 'left',
      kind: 'rows',
      label: 'Left',
      x: 205,
      y: 250,
      rotation: -14,
      categoryId: 'cat_std',
      rowCount: 6,
      seatsPerRow: 8,
      seatSpacing: 22,
      rowSpacing: 26,
      curve: 0,
      rowLabels: LETTERS,
      rowLabelPosition: 'left',
      seatLabels: NUMBERS,
    },
    {
      id: 'right',
      kind: 'rows',
      label: 'Right',
      x: 795,
      y: 250,
      rotation: 14,
      categoryId: 'cat_std',
      rowCount: 6,
      seatsPerRow: 8,
      seatSpacing: 22,
      rowSpacing: 26,
      curve: 0,
      rowLabels: LETTERS,
      rowLabelPosition: 'right',
      seatLabels: { scheme: 'numbers', start: '1', direction: 'reverse' },
    },
    {
      id: 't1',
      kind: 'round-table',
      label: 'Table 1',
      x: 120,
      y: 500,
      rotation: 0,
      categoryId: 'cat_table',
      radius: 30,
      seatCount: 8,
      seatLabels: NUMBERS,
    },
    {
      id: 't2',
      kind: 'round-table',
      label: 'Table 2',
      x: 270,
      y: 500,
      rotation: 0,
      categoryId: 'cat_table',
      radius: 30,
      seatCount: 8,
      seatLabels: NUMBERS,
    },
    {
      id: 't3',
      kind: 'round-table',
      label: 'Table 3',
      x: 120,
      y: 650,
      rotation: 0,
      categoryId: 'cat_table',
      radius: 30,
      seatCount: 6,
      seatLabels: NUMBERS,
    },
    {
      id: 't4',
      kind: 'round-table',
      label: 'Table 4',
      x: 270,
      y: 650,
      rotation: 0,
      categoryId: 'cat_table',
      radius: 30,
      seatCount: 6,
      seatLabels: NUMBERS,
    },
    {
      id: 't5',
      kind: 'rect-table',
      label: 'Table 5',
      x: 470,
      y: 570,
      rotation: 0,
      categoryId: 'cat_table',
      width: 130,
      height: 48,
      seats: { top: 4, right: 1, bottom: 4, left: 1 },
      seatLabels: NUMBERS,
    },
    {
      id: 'ga',
      kind: 'area',
      label: 'Standing',
      x: 770,
      y: 560,
      rotation: 0,
      categoryId: 'cat_ga',
      width: 260,
      height: 160,
      capacity: 150,
    },
    {
      id: 'bar',
      kind: 'shape',
      shape: 'ellipse',
      label: 'Bar',
      x: 900,
      y: 715,
      rotation: 0,
      width: 130,
      height: 50,
      fill: '#a16207',
    },
    {
      id: 'entrance',
      kind: 'text',
      label: '↓ Entrance',
      x: 500,
      y: 750,
      rotation: 0,
      fontSize: 16,
      color: '#475569',
    },
  ],
  seatOverrides: {
    'center:5:0': { accessible: true },
    'center:5:1': { accessible: true },
    'center:5:12': { accessible: true },
    'center:5:13': { accessible: true },
    't5:0:4': { categoryId: null },
  },
}

/** A few pre-sold seats so the guest view shows sold-out styling right away. */
export const SAMPLE_SALES: SalesState = {
  soldSeats: {
    'center:0:6': 'order_demo',
    'center:0:7': 'order_demo',
    'center:1:5': 'order_demo',
    'center:1:6': 'order_demo',
    'left:2:3': 'order_demo',
    'left:2:4': 'order_demo',
    't2:0:0': 'order_demo',
    't2:0:1': 'order_demo',
    't2:0:2': 'order_demo',
  },
  areaSold: { ga: 37 },
  orders: [],
}
